//задания на уровень
let taskName = "quiz21";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"Бразилия",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"США(Мост Золотые Ворота)",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"Россия",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"Финляндия",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:"Чехия (Прага)"
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:"Литва",
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:"Бельгия",
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"Украина",
			secTask:20,
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Индия",
			},
 	task10 = {task:``,
			pict:"./images/10.gif",
			answer:"Испания"
			}
]			