//задания на уровень
let taskName = "quiz22";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"Пифагор",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"Колумб",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"Ньютон",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"Эйнштейн",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:"Нельсон"
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:"Паганини",
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:"Гримм",
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"Грибоедов",
			secTask:20,
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Морзе",
			},
 	task10 = {task:``,
			pict:"./images/10.jpg",
			answer:"Дюма"
			},
 	task11 = {task:``,
			pict:"./images/11.jpg",
			answer:"Сократ/Аристотель"
			}
]			