//задания на уровень
let taskName = "quiz14";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"51 штат",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"Амели",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"Бойцовский клуб",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"Большой Лебовски",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:"Четверг"
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:"Матрица",
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:"Прощайте псы",
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"Фантастические твари и где они обитают",
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Фантомас",
			},
 	task10 = {task:``,
			pict:"./images/10.jpg",
			answer:"Эффект бабочки"
			}
]			