//задания на уровень
let taskName = "quiz04";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			sizeTask: `9rem`,
			sizeFormatAnswer:"9rem",
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
			answer:"Кто сильнее вас",
			},
 	task2 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/02.jpg",
			// audio:"./music/02.mp3",
//			secAnswer:,
			answer:"Завтра",
			}
			,
 	task3 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/03.jpg",
			// audio:"./music/03.mp3",
//			secAnswer:,
			answer:"Мудр",
			},
 	task4 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/04.jpg",
			// audio:"./music/04.mp3",
//			secAnswer:,
			answer:"Без удовольствия",
			},
 	task5 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/05.jpg",
				// audio:"./music/05.mp3",
//			secAnswer:,
			answer:"Памятных шрамов",
			},
 	task6 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/06.jpg",
				// audio:"./music/06.mp3",
//			secAnswer:,
			answer:"Нужных",
			},
 	task7 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/07.jpg",
				// audio:"./music/07.mp3",
//			secAnswer:,
			answer:"Была влюблена",
			},
 	task8 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/08.jpg",
				// audio:"./music/08.mp3",
//			secAnswer:,
			answer:"Любил",
			},
 	task9 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/09.jpg",
				// audio:"./music/09.mp3",
//			secAnswer:,
			answer:"Подхалимствуй",
			},
 	task10 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/10.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Несчастье"
			},
 	task11 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/11.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Звенит будильник"
			},
 	task12 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/12.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Повторимо"
			},
 	task13 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/13.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Воспитанный"
			},
 	task14 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/14.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Хороший знак"
			},
 	task15 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/15.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"В краю родном"
			},
 	task16 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/16.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Сердце герцогини"
			},
 	task17 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/17.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Пирожник"
			},
 	task18 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/18.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Веревочка"
			},
 	task19 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/19.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Пистолета"
			},
 	task20 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/20.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Плетень"
			}
]			