//задания на уровень
const tasks = [
 	task1 = {task:``,
			sec:30,
			sizeFormatAnswer: `9rem`,
			formatAnswer:"",
			pict:"./Images/doodle_ (01).jpg"},
	task2 = {task:``,
 			formatAnswer:``,
			sec:30,
 			pict:"./Images/doodle_ (02).jpg"},
	task3 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (03).jpg"},
	task4 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (04).jpg"},
	task5 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (05).jpg"},
	task6 = {task:``,
			sec:30,
			sizeTask:``,
			sizeFormatAnswer: `7rem`,
			formatAnswer:``,
			pict:"./Images/doodle_ (06).jpg"},
	task7 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (07).jpg"},
 	task8 = {task:``,
			sec:30,
			sizeFormatAnswer: `9rem`,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (08).jpg"},
	task9 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (09).jpg"},
	task10 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (10).jpg"},
	task11 = {task:``,
			sec:30,
			sizeTask:``,
			sizeFormatAnswer: `7rem`,
			formatAnswer:``,
			pict:"./Images/doodle_ (11).jpg"},
	task12 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (12).jpg"},
 	task13 = {task:``,
			sec:30,
			sizeFormatAnswer: `9rem`,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (13).jpg"},
	task14 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (14).jpg"},
	task15 = {task:``,
			sec:30,
			sizeFormatAnswer: ``,
			sizeTask:``,
			formatAnswer:``,
			pict:"./Images/doodle_ (15).jpg"},
 	task16 = {task:``,
			sec:30,
			formatAnswer:``,
			pict:"./Images/doodle_ (16).jpg"}
];
	



const answers = [
  	task1 = {
			sec:12, formatAnswer:"",
			task:"Роршах",
			pict:""},
	task2 = {
			sec:12, formatAnswer:"",
 			task:`Виктор Цой`,
 			pict:""},
	task3 = {
			sec:12, formatAnswer:"",
			task:`Ш.Перро, Грим`,
			pict:""},
	task4 = {
			sec:12, formatAnswer:"",
			task:`Николай Гоголь`,
			pict:""},
	task5 = {
			sec:12, formatAnswer:"",
			task:`Антоан Экзюпери`,
			pict:""},
	task6 = {
			sec:12, formatAnswer:"",
			task:`Михаил Булгаков`,
			pict:""},
	task7 = {
			sec:12, formatAnswer:"",
			task:`Марк Твен`,
			pict:""},
	task8 = {
			sec:12, formatAnswer:"",
			task:`Морзе`,
			pict:""},
	task9 = {
			sec:12, formatAnswer:"",
			task:`Вильям Шекспир`,
			pict:""},
	task10 = {
			sec:12, formatAnswer:"",
			task:`Майкл Джексон`,
			pict:""},
	task11 = {
			sec:12, formatAnswer:"",
 			task:`Нестеров`,
 			pict:""},
	task12 = {
			sec:12, formatAnswer:"",
			task:`Фёдор Шаляпин`,
			pict:""},
	task13 = {
			sec:12, formatAnswer:"",
			task:`Самуил Маршак`,
			pict:""},
	task14 = {
			sec:12, formatAnswer:"",
			task:`Леонид Гайдай`,
			pict:""},
	task15 = {
			sec:12, formatAnswer:"",
			task:`Александр Грин`,
			pict:""},
	task16 = {
			sec:12, formatAnswer:"",
			task:`Агния Барто`,
			pict:""}
];
			

