//задания на уровень
taskName = "quiz02";
const pauseAfterTask = 4; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:1,
			sizeTask: `9rem`,
			sizeFormatAnswer:"9rem",
			pict:"./images/01.png",
			// audio:"./images/01.mp3",
			secAnswer:3,
			answer:"Порту",
			},
 	task2 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/02.png",
			// audio:"./music/02.mp3",
//			secAnswer:,
			answer:"Анталия",
			}
			,
 	task3 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/03.png",
			// audio:"./music/03.mp3",
//			secAnswer:,
			answer:"Стамбул",
			},
 	task4 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/04.png",
			// audio:"./music/04.mp3",
//			secAnswer:,
			answer:"Рим",
			},
 	task5 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/05.png",
				// audio:"./music/05.mp3",
//			secAnswer:,
			answer:"Афины",
			},
 	task6 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/06.png",
				// audio:"./music/06.mp3",
//			secAnswer:,
			answer:"Мельбурн",
			},
 	task7 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/07.png",
				// audio:"./music/07.mp3",
//			secAnswer:,
			answer:"Берлин",
			},
 	task8 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/08.png",
				// audio:"./music/08.mp3",
//			secAnswer:,
			answer:"Полтава",
			},
 	task9 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/09.png",
				// audio:"./music/09.mp3",
//			secAnswer:,
			answer:"Варна",
			},
 	task10 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/10.png",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Джакарта",
			}
]			