//задания на уровень
let taskName = "quiz13";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"4 комнаты",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"5ый элемент",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"Джуманджи",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"MIB",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:"Крестный отец"
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:"Брюс Всемогущий",
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:"Гладиатор",
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"Дракула",
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Кудряшка Сью",
			},
 	task10 = {task:``,
			pict:"./images/10.jpg",
			answer:"Лицо со шрамом"
			}
]			