//задания на уровень
let taskName = "quiz15";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"Каспер",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"Взрыв из прошлого",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"Мулен Руж",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"Парк Юрского периода",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:"Реквием по мечте"
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:"Спасти рядового Раяна",
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:"Список Шиндлера",
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"Схватка",
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Тёмный рыцарь",
			},
 	task10 = {task:``,
			pict:"./images/10.jpg",
			answer:"Умница Уилл Хантинг"
			}
]			