//задания на уровень
let taskName = "quiz16";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"Железный человек",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"ХХХ",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"Лара Крофт",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"Крепкий орешек",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:"Малышка на миллион"
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:"Мортал Комбат",
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:"Робокоп",
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"Рокки",
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Семь",
			},
 	task10 = {task:``,
			pict:"./images/10.jpg",
			answer:"Такси"
			}
]			