//задания на уровень
let taskName = "quiz01";
const pauseAfterTask = 4; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:1,
			sizeTask: `9rem`,
			sizeFormatAnswer:"9rem",
			pict:"",
			audio:"./music/01.mp3",
			secAnswer:3,
			answer:"Красотка",
			pict:""},
 	task2 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/02.mp3",
//			secAnswer:,
			answer:"Звездные войны",
			pict:""}
			,
 	task3 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/03.mp3",
//			secAnswer:,
			answer:"Стражи галактики",
			pict:""},
 	task4 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/04.mp3",
//			secAnswer:,
			answer:"Телохранитель",
			pict:""},
 	task5 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/05.mp3",
//			secAnswer:,
			answer:"Пираты карибского моря",
			pict:""},
 	task6 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/06.mp3",
//			secAnswer:,
			answer:"Три Мушкетера",
			pict:""},
 	task7 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/07.mp3",
//			secAnswer:,
			answer:"Хороший,плохой и злой",
			pict:""},
 	task8 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/08.mp3",
//			secAnswer:,
			answer:"Миссия невыполнима",
			pict:""},
 	task9 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/09.mp3",
//			secAnswer:,
			answer:"Люди в чёрном",
			pict:""},
 	task10 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Полицейская академия",
			pict:""}
]			