//задания на уровень
let taskName = "quiz05";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.png",
			// audio:"./images/01.mp3",
			secAnswer:10,
			formatAnswer:"Два слова на русском языке",
			answer:"Вынос мозга",
			},
 	task2 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/02.png",
			// audio:"./music/02.mp3",
//			secAnswer:,
			formatAnswer:"Три слова на русском языке",
			answer:"Картошка в мундире",
			}
			,
 	task3 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/03.png",
			// audio:"./music/03.mp3",
//			secAnswer:,
			formatAnswer:"Имя Фамилия",
			answer:"Люк Бессон",
			},
 	task4 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/04.png",
			// audio:"./music/04.mp3",
//			secAnswer:,
			formatAnswer:"Два слова на русском языке",
			answer:"Солнце глаза режет",
			},
 	task5 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/05.png",
				// audio:"./music/05.mp3",
//			secAnswer:,
			formatAnswer:"Два слова на русском языке",
			answer:"Сопротивление бесполезно"
			},
 	task6 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/06.png",
				// audio:"./music/06.mp3",
//			secAnswer:,
			formatAnswer:"Три слова на русском языке",
			answer:"Яблоки на снегу",
			},
 	task7 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/07.png",
				// audio:"./music/07.mp3",
//			secAnswer:,
			formatAnswer:"Три слова на русском языке",
			answer:"Кот в сапогах/Два сапога пара",
			},
 	task8 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/08.jpg",
				// audio:"./music/08.mp3",
//			secAnswer:,
			formatAnswer:"Два слова на русском языке",
			answer:"Бенгальский тигр",
			},
 	task9 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/09.png",
				// audio:"./music/09.mp3",
//			secAnswer:,
			formatAnswer:"Два слова на русском языке",
			answer:"Двойные стандарты",
			},
 	task10 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/10.png",
				// audio:"./music/10.mp3",
//			secAnswer:,
			formatAnswer:"Два слова на русском языке",
			answer:"Нога затекла"
			},
 	task11 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/11.png",
				// audio:"./music/10.mp3",
//			secAnswer:,
			formatAnswer:"Три слова на русском языке",
			answer:"Часы 12 бьют"
			},
 	task12 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/12.png",
				// audio:"./music/10.mp3",
//			secAnswer:,
			formatAnswer:"Два слова на русском языке",
			answer:"Лёд тронулся"
			},
 	task13 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/13.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			formatAnswer:"Два слова на русском языке",
			answer:"Аккумулятор сел/Батарейка села"
			},
 	task14 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/14.png",
				// audio:"./music/10.mp3",
//			secAnswer:,
			formatAnswer:"Три слова на русском языке",
			answer:"Кровь носом пошла"
			},
 	task15 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/15.png",
				// audio:"./music/10.mp3",
//			secAnswer:,
			formatAnswer:"Три слова на русском языке",
			answer:"Прижаться к обочине!"
			}
]			