//задания на уровень
let taskName = "quiz16";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"Грязные танцы",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"100 дней лета",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"Отпуск по обмену",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"Дневник Бриджит Джонс",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:"Ешь молись люби"
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:"Ла ла ленд",
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:"Правила съема метод Хитча",
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"Притоврись моей женой",
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Реальная любовь",
			},
 	task10 = {task:``,
			pict:"./images/10.jpg",
			answer:"Чего хотят женщины"
			}
]			