//задания на уровень
taskName = "quiz03";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			sizeTask: `9rem`,
			sizeFormatAnswer:"9rem",
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
			answer:"Роршах",
			},
 	task2 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/02.jpg",
			// audio:"./music/02.mp3",
//			secAnswer:,
			answer:"Цой",
			}
			,
 	task3 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/03.jpg",
			// audio:"./music/03.mp3",
//			secAnswer:,
			answer:"Шарль Перро, Гримм",
			},
 	task4 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/04.jpg",
			// audio:"./music/04.mp3",
//			secAnswer:,
			answer:"Гоголь",
			},
 	task5 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/05.jpg",
				// audio:"./music/05.mp3",
//			secAnswer:,
			answer:"Экзюпери",
			},
 	task6 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/06.jpg",
				// audio:"./music/06.mp3",
//			secAnswer:,
			answer:"А.Барто",
			},
 	task7 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/07.jpg",
				// audio:"./music/07.mp3",
//			secAnswer:,
			answer:"Марк Твен",
			},
 	task8 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/08.jpg",
				// audio:"./music/08.mp3",
//			secAnswer:,
			answer:"Морзе",
			},
 	task9 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/09.jpg",
				// audio:"./music/09.mp3",
//			secAnswer:,
			answer:"Майкл Джексон",
			},
 	task10 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/10.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Шекспир"
			}
]			