//задания на уровень
let taskName = "quiz25";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"Алкоголики - это наш профиль",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"Пасть порву, моргала выколю",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"Кто ж его посадит, он же памятник",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"Руссо туристо - облико морале!",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:`Шампанское по утрам пьют аристократы и дегенераты`
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:`Несчастные случаи на стройке были? Будут.`,
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:`Я требую продолжения банкета!`,
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"И шо я в тебя такой влюбленный, а?",
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Гюльчитай, открой личико.",
			},
 	task10 = {task:``,
			pict:"./images/10.jpg",
			answer:"Беги, дядь Мить!"
			}
]			