//задания на уровень
let taskName = "quiz21";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:60,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:15,
//			formatAnswer:"",
			answer:"Винная карта",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"Алмазам даются имена",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"Что бы похудеть/сбросить вес",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"Донарская кровь/сдача крови",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:`Средство/шампунь от облысения`
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:`Душу`,
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:`Отмывать деньги`,
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"Хусейн Болт",
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Секс, наркотики и рок-н-ролл",
			},
 	task10 = {task:``,
			pict:"./images/10.jpg",
			answer:"Зайцы"
			}
]			