//задания на уровень
let taskName = "quiz05";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"От заката до рассвета",
			},
 	task2 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/02.jpg",
			// audio:"./music/02.mp3",
//			secAnswer:,
//			formatAnswer:"",
			answer:"Американские янки в Африке",
			}
			,
 	task3 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/03.jpg",
			// audio:"./music/03.mp3",
//			secAnswer:,
//			formatAnswer:"",
			answer:"Гудзонский ястреб",
			},
 	task4 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/04.jpg",
			// audio:"./music/04.mp3",
//			secAnswer:,
//			formatAnswer:"",
			answer:"Криминальное чтиво",
			},
 	task5 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/05.jpg",
				// audio:"./music/05.mp3",
//			secAnswer:,
//			formatAnswer:"",
			answer:"На гребне волны"
			},
 	task6 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/06.jpg",
				// audio:"./music/06.mp3",
//			secAnswer:,
			answer:"Петля времени",
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:"Плохой Санта",
			},
 	task8 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/08.jpg",
				// audio:"./music/08.mp3",
//			secAnswer:,
//			formatAnswer:"",
			answer:"Побег из Шоушенка",
			},
 	task9 = {task:``,
//			secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/09.jpg",
				// audio:"./music/09.mp3",
//			secAnswer:,
//			formatAnswer:"",
			answer:"Трудная мишень",
			},
 	task10 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"./images/10.jpg",
				// audio:"./music/10.mp3",
//			secAnswer:,
//			formatAnswer:"",
			answer:"Цельнометаллическая оболочка"
			}
]			