//задания на уровень
let taskName = "quiz23";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.png",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"Люди в черном",
			},
 	task2 = {task:``,
			pict:"./images/02.png",
			answer:"Коммандо",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.png",
			answer:"Бойцовский клуб",
			},
 	task4 = {task:``,
			pict:"./images/04.png",
			answer:"Тупой и еще тупее",
			},
 	task5 = {task:``,
			pict:"./images/05.png",
			answer:"Человек Паук"
			},
 	task6 = {task:``,
			pict:"./images/06.png",
			answer:"Матрица",
			},
 	task7 = {task:``,
			pict:"./images/07.png",
			answer:"Цельнометаллическая оболочка",
			},
 	task8 = {task:``,
			pict:"./images/08.png",
			answer:"1+1",
			},
 	task9 = {task:``,
			pict:"./images/09.png",
			answer:"Изо всех сил",
			},
 	task10 = {task:``,
			pict:"./images/10.png",
			answer:"Назад в будущее/Форсаж"
			}
]			