//задания на уровень
let taskName = "quiz21";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:30,
			pict:"./images/01.jpg",
			// audio:"./images/01.mp3",
			secAnswer:10,
//			formatAnswer:"",
			answer:"Иван Васильевич меняет профессию",
			},
 	task2 = {task:``,
			pict:"./images/02.jpg",
			answer:"Призрак",
			}
			,
 	task3 = {task:``,
			pict:"./images/03.jpg",
			answer:"1+1",
			},
 	task4 = {task:``,
			pict:"./images/04.jpg",
			answer:"Оно",
			},
 	task5 = {task:``,
			pict:"./images/05.jpg",
			answer:"День выборов"
			},
 	task6 = {task:``,
			pict:"./images/06.jpg",
			answer:"Плохой Санта",
			},
 	task7 = {task:``,
			pict:"./images/07.jpg",
			answer:"ДМБ",
			},
 	task8 = {task:``,
			pict:"./images/08.jpg",
			answer:"Достучаться до небес",
			secTask:20,
			},
 	task9 = {task:``,
			pict:"./images/09.jpg",
			answer:"Вспомнить всё",
			},
 	task10 = {task:``,
			pict:"./images/10.jpg",
			answer:"300 спартанцев"
			}
]			