//задания на уровень
let taskName = "quiz11";
const pauseAfterTask = 30; //sec пауза после уровня на подумать
const tasks = [
 	task1 = {task:``,
			secTask:5 ,
			sizeTask: `9rem`,
			sizeFormatAnswer:"9rem",
			pict:"",
			audio:"./music/01.mp3",
			secAnswer:5,
			answer:"Ну Погоди",
			pict:""},
 	task2 = {task:``,
			// secTask:,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/02.mp3",
			secAnswer: 3,
			answer:"Пяточкин",
			pict:""}
			,
 	task3 = {task:``,
			secTask: 5,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/03.mp3",
//			secAnswer:,
			answer:"Моана",
			pict:""},
 	task4 = {task:``,
			secTask: 4,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/04.mp3",
//			secAnswer:,
			answer:"Шрек",
			pict:""},
 	task5 = {task:``,
			secTask: 2,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/05.mp3",
//			secAnswer:,
			answer:"Бременские музыканты",
			pict:""},
 	task6 = {task:``,
			secTask: 10,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/06.mp3",
//			secAnswer:,
			answer:"Умка",
			pict:""},
 	task7 = {task:``,
			secTask: 10,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/07.mp3",
//			secAnswer:,
			answer:"Мама для мамонтенка",
			pict:""},
 	task8 = {task:``,
			secTask: 15,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/08.mp3",
//			secAnswer:,
			answer:"Алладин",
			pict:""},
 	task9 = {task:``,
			secTask:15,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/09.mp3",
//			secAnswer:,
			answer:"Мишки Гамми",
			pict:""},
 	task10 = {task:``,
			secTask: 15,
			sizeTask: ``,
			sizeFormatAnswer:"",
			pict:"",
			audio:"./music/10.mp3",
//			secAnswer:,
			answer:"Русалка",
			pict:""}
]			